No error on missing-field-initializers warning
Linux now has some uninitialized struct fields.
EVDI will fail to build if this is treated as an error.

```
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/travis/build/mintel/evdi/module/evdi.mod.o
/home/travis/build/mintel/evdi/module/evdi.mod.c:15:2: error: missing initializer for field ‘num_orcs’ of ‘struct mod_arch_specific’ [-Werror=missing-field-initializers]
  .arch = MODULE_ARCH_INIT,
  ^
In file included from ./include/linux/module.h:24:0,
                 from /home/travis/build/mintel/evdi/module/evdi.mod.c:1:
./arch/x86/include/asm/module.h:10:15: note: ‘num_orcs’ declared here
  unsigned int num_orcs;
               ^
```