Fix missing struct initializers reported by clang
Clang wants all members of a struct to be initialized. It issues the
following warnings on the code, before the fix

evdi_lib.c:307:37: error: missing field 'dev_index' initializer
      [-Werror,-Wmissing-field-initializers]
        struct drm_evdi_connect cmd = { 0 };
                                            ^
evdi_lib.c:313:55: error: missing field 'y1' initializer
[-Werror,-Wmissing-field-initializers]
        struct drm_clip_rect kernelDirts[MAX_DIRTS] = { { 0 } };
                                                               ^